version: '3.7'

services:
  app:
    image: node:16-alpine
    command: sh -c "npm install && npm run start"
    ports:
      - "9000:3000"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - MONGODB_CONNSTRING=mongodb://lingo:password@mongo

  mongo:
    image: mongo:4.4.15
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lingo
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - lingodb:/data/db
      - lingodb_config:/data/configdb

volumes:
  lingodb:
  lingodb_config:

